import { env } from "@/env";

/**
 * Email assets hosted on CDN (R2)
 *
 * These URLs are generated by running:
 *   npx tsx scripts/upload-email-assets.ts
 *
 * Using CDN URLs ensures images display correctly in email clients
 * like Gmail, which have strict requirements for external images.
 */

// Logo URL hosted on R2 CDN
// Generated by: pnpm upload:email-assets
export const EMAIL_LOGO_URL = `${env.R2_PUBLIC_URL}/email/logo.png`;

// Brand colors for emails (matching the design system)
export const EMAIL_COLORS = {
  primary: "#7c3aed",
  primaryLight: "#f3f0ff",
  text: {
    primary: "#1a1a1a",
    secondary: "#525252",
    muted: "#8898aa",
  },
  border: "#e6ebf1",
  background: "#f6f9fc",
  white: "#ffffff",
  priority: {
    urgent: "#dc2626",
    high: "#ea580c",
    normal: "#2563eb",
    low: "#16a34a",
  },
} as const;

// Common email footer links
export const EMAIL_LINKS = {
  website: "https://xchatlife.com",
  support: "https://xchatlife.com/support",
  unsubscribe: "https://xchatlife.com/unsubscribe",
} as const;
